<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>syslog-ng.conf</string>
	</array>
	<key>name</key>
	<string>Syslog</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((d|f|s)_\w+)\b</string>
			<key>name</key>
			<string>string.unquoted</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b^(source|destination|filter|log|options)\b</string>
			<key>name</key>
			<string>support.class</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(crit|debug|err|emerg|info|notice|warn|auth|authpriv|cron|daemon|mail|news|kern|lpr|user|uucp|off|no|on|yes|allow|required|no-parse|mysql)\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(udp|tcp|ip|port|authentication|encrypt|chain_hostnames|flush_lines|use_dns|use_fqdn|owner|group|perm|stats_freq|bad_hostname|file|level|facility|source|filter|destination|usertty|pipe|sql|type|username|password|database|host|table|columns|values|indexes|create_dirs|system|internal|follow_freq|flags)(?=\s*\()</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\"[\w\.\/]+\")</string>
			<key>name</key>
			<string>string.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\$\w+)</string>
			<key>name</key>
			<string>variable</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?):\d{1,5}\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(\d+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.syslog</string>
	<key>uuid</key>
	<string>12513600-AF27-415F-899D-3AB57C696A47</string>
</dict>
</plist>
